@Biblioteca_HostAddress = http://localhost:5180

GET {{Biblioteca_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{Biblioteca_HostAddress}}/api/Auth/register
Content-Type: application/json

{
  "nome": "Felipe",
  "email": "felipe@email.com",
  "password": "MinhaSenha123"
}

###