@Biblioteca_HostAddress = http://localhost:5180

GET {{Biblioteca_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Biblioteca_HostAddress}}/api/Auth/register
Content-Type: application/json

{
  "nome": "David",
  "email": "David111@email.com",
  "password": "MinhaSenha123"
}

###

POST {{Biblioteca_HostAddress}}/api/Auth/enviar-codigo
Content-Type: application/json

{
  "email": "felipelsmovio@gmail.com"
}

###

###
POST {{Biblioteca_HostAddress}}/api/Auth/verificar-email
Content-Type: application/json

{
  "Id": "f96b8704-eb4c-44b8-b251-abf7cebd07cc",
  "codigo": "779282"
}

###
POST {{Biblioteca_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "email": "felipelsmovio@gmail.com",
  "password": "MinhaSenha123"
}
